### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by ling8yue** [permanentCH5/GeoInfoNet#4]
![123](https://github.com/permanentCH5/GeoInfoNet/assets/146167913/0e70c914-476c-4c48-a132-8f2c1ffe17a7)

I ran into this error when I ran the code, I'm a noob, I would like to ask if there are any big guys who have encountered this problem and solved it

**Comment by permanentCH5** [comment]
Please carefully check whether cuda and torch are correctly installed.
